# Generated by Django 5.1.2 on 2024-10-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=25, unique=True, verbose_name='Səhifə adı')),
                ('meta_title', models.CharField(max_length=25, verbose_name='Meta başlıq')),
                ('meta_description', models.TextField(max_length=250, verbose_name='Meta açıqlama')),
            ],
        ),
    ]
