# Generated by Django 5.1.2 on 2024-10-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seomodel',
            name='meta_description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='seomodel',
            name='meta_title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='seomodel',
            name='page_name',
            field=models.CharField(error_messages={'unique': 'Bu səhifə adı artıq mövcuddur, xahiş edirəm başqa bir ad daxil edin.'}, max_length=25, unique=True),
        ),
    ]
