# Generated by Django 5.1.2 on 2024-10-30 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_alter_seomodel_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seomodel',
            name='meta_description',
            field=models.TextField(max_length=250, validators=[django.core.validators.MaxLengthValidator(250, message='Meta açıqlama 250 simvoldan uzun ola bilməz.')]),
        ),
        migrations.AlterField(
            model_name='seomodel',
            name='meta_title',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, message='Meta başlıq 25 simvoldan uzun ola bilməz.')]),
        ),
        migrations.AlterField(
            model_name='seomodel',
            name='page_name',
            field=models.CharField(error_messages={'unique': 'Bu səhifə adı artıq mövcuddurrr-, xahiş edirəm başqa bir ad daxil edin.'}, max_length=20, unique=True),
        ),
    ]
