# Generated by Django 5.1.2 on 2024-10-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_alter_seomodel_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seomodel',
            name='page_name',
            field=models.CharField(error_messages={'unique': 'Bu səhifə adı artıq mövcuddur, xahiş edirəm başqa bir ad daxil edin.'}, max_length=20, unique=True),
        ),
    ]
