# Generated by Django 5.1.2 on 2024-10-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='content_demo',
        ),
    ]
