# Generated by Django 5.1.2 on 2024-10-24 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': 'E-posta sahəsi boş qala bilməz.', 'invalid': 'Keçərli bir e-posta ünvanı daxil edin.', 'max_length': 'E-posta ən çox 50 simvol olmalıdır.', 'null': 'E-posta sahəsi boş qala bilməz.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'İsim alanı boş bırakılamaz.', 'max_length': 'İsim en fazla 30 karakter olmalıdır.', 'null': 'İsim alanı boş bırakılamaz.'}, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'Soyisim sahəsi boş qala bilməz.', 'max_length': 'Soyisim ən çox 30 simvol olmalıdır.', 'null': 'Soyisim sahəsi boş qala bilməz.'}, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'blank': 'Telefon nömrəsi sahəsi boş qala bilər.', 'invalid': 'Keçərli bir telefon nömrəsi daxil edin.', 'max_length': 'Telefon nömrəsi ən çox 15 simvol olmalıdır.', 'null': 'Telefon nömrəsi sahəsi boş qala bilər.', 'unique': 'Bu telefon nömrəsi artıq götürülüb.'}, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon nömrəsi '+994775685605' formatında olmalıdır.", regex='^\\+?[0-9]{9,20}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'İstifadəçi adı sahəsi boş qala bilməz.', 'max_length': 'İstifadəçi adı ən çox 20 simvol olmalıdır.', 'null': 'İstifadəçi adı sahəsi boş qala bilməz.', 'unique': 'Bu istifadəçi adı artıq götürülüb.'}, max_length=20, unique=True),
        ),
    ]
