# Generated by Django 5.1.2 on 2024-10-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'Ad sahəsi boş qala bilməz.', 'max_length': 'Ad ən çox 30 simvol olmalıdır.', 'null': 'Ad sahəsi boş qala bilməz.'}, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'Soyad sahəsi boş qala bilməz.', 'max_length': 'Soyad ən çox 30 simvol olmalıdır.', 'null': 'Soyad sahəsi boş qala bilməz.'}, max_length=30),
        ),
    ]
