# Generated by Django 5.1.2 on 2024-10-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctedtext',
            options={'ordering': ['-created_at'], 'verbose_name': 'Düzəldilmiş Mətn', 'verbose_name_plural': 'Düzəldilmiş Mətinlər'},
        ),
        migrations.AlterModelOptions(
            name='deletedtext',
            options={'ordering': ['-deleted_at'], 'verbose_name': 'Silinmiş Mətn', 'verbose_name_plural': 'Silinmiş Mətinlər'},
        ),
    ]
