# Generated by Django 5.1.2 on 2024-10-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
